export { default as Awards } from './awards/Awards'
export { default as NavLinks } from './navlinks/NavLinks'
export { default as ProjectCard } from './projectcard/ProjectCard'
export { default as TechStack } from './techstack/TechStack'
export { default as FooterIcons } from './footer-icons/FooterIcons'